spring:
  profiles:
    active: docker
server:
  port: 8081

---
spring:
  profiles: local
  kafka:
    template:
      default-topic: transfer-events
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: transfer-events-group
    producer:
      bootstrap-servers:
        -   localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

---
spring:
  profiles: docker
  kafka:
    template:
      default-topic: transfer-events
    consumer:
      bootstrap-servers: kafka:9093
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: transfer-events-group
    producer:
      bootstrap-servers:
        -   kafka:9093
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
